"""
Test script to generate a MusicXML file with all drum notation positions and noteheads.
Creates a simple demo with one note for each of the 10 drum instruments.
"""
from music21 import stream, note, clef, metadata

def generate_drum_notation_demo_xml(output_path="drum_notation_demo.musicxml"):
    """
    Generate a MusicXML file with all drum instruments positioned correctly
    on the staff with appropriate notehead types.
    """
    # Map each instrument to (staff position, notehead type, display name, MIDI note)
    drum_map = [
        # (step, octave, notehead, displayName, MIDI_pitch)
        # Staff positions are mapped via step/octave for percussion clef
        # We'll use Unpitched notes and set displayStep/displayOctave for staff placement
        (('F', 4), 'normal', 'Bass Drum (Kick)', 36),                # Bottom space - C1
        (('B', 4), 'normal', 'Snare Drum', 38),                      # Third space (middle) - D1
        (('B', 4), 'x', 'Cross Stick (Rim Click)', 37),              # Third space, cross - C#1 -> Changed to C#2 (37)
        (('E', 5), 'normal', 'High Tom (Rack Tom 1)', 50),           # Top space - D2
        (('D', 5), 'normal', 'Mid Tom (Rack Tom 2)', 47),            # Fourth line - B1
        (('A', 4), 'normal', 'Floor Tom (Tom 3)', 41),               # Second space - F1 -> Changed to F2 (41)
        (('G', 5), 'x', 'Hi-Hat (with stick)', 42),                  # Space above top line - F#1
        (('D', 4), 'x', 'Hi-Hat (with foot)', 44),                   # Space below bottom line - G#1
        (('F', 5), 'x', 'Ride Cymbal (bow)', 51),                    # Top line - D#2
        (('F', 5), 'circle-x', 'Ride Cymbal (bell)', 53),            # Top line, circle-x - F2 -> Changed to F3 (53)
        (('A', 5), 'x', 'Crash Cymbal 1 (Left)', 49),                # 1st ledger line above - Changed to C#3 (49)
        (('C', 6), 'x', 'Crash Cymbal 2 (Right)', 57),               # 2nd ledger space above - A2 -> Changed to A3 (57)
    ]

    print("=" * 70)
    print("  Drum Notation MusicXML Generator")
    print("=" * 70)
    print(f"\nGenerating MusicXML with {len(drum_map)} drum instruments...\n")

    # Create the stream
    s = stream.Score()
    s.append(metadata.Metadata())
    s.metadata.title = "Drum Notation Demo - All Instruments"
    s.metadata.composer = "Generated by music21"

    # Create part with percussion clef and proper drum instrument
    part = stream.Part()
    part.append(clef.PercussionClef())
    part.id = "Percussion"
    
    # Set the instrument to drums (MIDI program 0, channel 10 for drums)
    from music21 import instrument
    drums = instrument.Instrument()
    drums.instrumentName = "Drumset"
    drums.midiProgram = 0  # Program 0
    drums.midiChannel = 9  # Channel 10 (0-indexed, so channel 9 = MIDI channel 10)
    part.insert(0, drums)

    # Split notes into four measures (3 notes each)
    notes_per_measure = 3
    measure_num = 1
    
    from music21 import layout
    
    for i in range(0, len(drum_map), notes_per_measure):
        measure = stream.Measure(number=measure_num)
        
        # Add notes for this measure
        for idx in range(i, min(i + notes_per_measure, len(drum_map))):
            (step, octave), notehead, name, midi_pitch = drum_map[idx]
            n = note.Note()
            n.pitch.midi = midi_pitch
            n.duration.quarterLength = 1.0  # Quarter note
            n.notehead = notehead
            n.displayStep = step
            n.displayOctave = octave
            n.stemDirection = 'up'
            n.addLyric(name)
            measure.append(n)
            print(f"✓ Added: {name:30s} | Position: {step}{octave} | Notehead: {notehead} | MIDI: {midi_pitch} | Measure: {measure_num}")
        
        # Add a system break after each measure to force a new line
        measure.append(layout.SystemLayout(isNew=True))
        
        part.append(measure)
        measure_num += 1

    s.append(part)

    # Write to file
    print(f"\n⏳ Writing MusicXML file to: {output_path}")
    s.write('musicxml', fp=output_path)
    
    import os
    if os.path.exists(output_path):
        file_size = os.path.getsize(output_path)
        print(f"✓ MusicXML file created successfully!")
        print(f"   File: {output_path}")
        print(f"   Size: {file_size} bytes")
        print(f"   Total notes: {len(drum_map)}")
    else:
        print(f"✗ Error: File was not created")

    print("\n💡 Open this file in MuseScore or any MusicXML viewer to see the notation")
    print("=" * 70)

if __name__ == "__main__":
    import os
    
    # Output to test_output directory
    output_dir = r"d:\Coding Files\GitHub\drumscore-be\test_output"
    os.makedirs(output_dir, exist_ok=True)
    
    output_file = os.path.join(output_dir, "drum_notation_demo.musicxml")
    
    try:
        generate_drum_notation_demo_xml(output_file)
    except Exception as e:
        print(f"\n✗ Error generating MusicXML: {e}")
        import traceback
        traceback.print_exc()
